---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
  - port: 80
  selector:
    name: hello-world-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: hello-world-app
  template:
    metadata:
      labels:
        name: hello-world-app
    spec:
      containers:
        - name: hello-world
          image: nginxdemos/hello # https://github.com/nginxinc/NGINX-Demos/tree/master/nginx-hello
          ports:
            - containerPort: 80
#  /usr/share/nginx/html
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: hello-world-app
spec:
  rules:
    - host: hello-world-dev.apps.rke1.test.2108.dk
      http:
        paths:
          - backend:
              serviceName: hello-world
              servicePort: 80
            path: /test